py_binary(
  name = "main",
  deps = ["//modules:comments_helpers"],
  srcs = ["main.py"],
)

py_library(
    name = "grammar_go_lexers",
    deps = [],
    visibility = ["//visibility:public"],
    srcs = ["GoLexer.py"]
)