/*
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWXOkkkkkkkO0000000000000000000000000000000000000000000000OOOO00OOOOOOOOOOOOOOOOOOOOO0000000000000000000000000000000000000000000000000000000000NWWWW
WWWW0c;;;;;;;cdxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxddxxxxxxxxxxxxxxxxxxxxxxxxxxdooxxxxxoc;::::;l0WWWW
WWWW0l;;;;;;;cdxxxxxxxxoloxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxc':dxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxc':dxxxxxxxxxxxxxxxxxxxxxxxxxc.'oxxxxo:;;;;;;l0WWWW
WWWWXo;;;;;;;coxxxxxxxd,.;dxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxl.
.cxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxl. .cxxxxxxxxxxxxxxxxxxxxxxxxl.
;dxxxl:;;;;;;oKWWWW WWWWNd;;;;;;;:oxxxxxxd; .cxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo'
'oxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo'   'oxxxxxxxxxxxxxxxxxxxxxxo.
.cxxdl;;;;;;;dNWWWW WWWWWk:;;;;;;;lxxxxxx:.   .oxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd;
:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd,    .:xxxxxxxxxxxxxxxxxxxxxd;
,dxdc;;;;;;:kWWWWW WWWWW0l;;;;;;;cdxxxxo.     :xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo.
,dxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo.     ,dxxxxxxxxxxxxxxxxxxxxd,
'oxo:;;;;;;l0WWWWW WWWWWXd:;;;;;;:oxxxxl.
:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdc'...'lxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdc'...'lxxxxxxxxxxxxxxxxxxxxxxo:,,,;lxdl;;;;;;:dXWWWWW
WWWWWWOc;;;;;;;cdxxxxo:;;;cdxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdddxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo:;;;;;;cOWWWWWW
WWWWWWXd;;;;;;;:oxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdc;;;;;;;dXWWWWWW
WWWWWWW0c;;;;;;;cdxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxooxxxxxxxxxxxxxxxxxl:;;;;;;cOWWWWWWW
WWWWWWWNx:;;;;;;;ldxxxxxxxxxxxxxxxxxxxxdc:oxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdc:oxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxc..lxxxxxxxxxxxxxxxoc;;;;;;:xNWWWWWWW
WWWWWWWWKo;;;;;;;:lxxxxxxxxxxxxxxxxxxxxc. ;dxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxc.
;dxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxl.  ,dxxxxxxxxxxxxxdc;;;;;;;oKWWWWWWWW
WWWWWWWWW0l;;;;;;;:oxxxxxxxxxxxxxxxxxxl.  .cxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxl.
.cxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo'   .:xxxxxxxxxxxxdc:;;;;;;l0WWWWWWWWW
WWWWWWWWWNOc;;;;;;;:oxxxxxxxxxxxxxxxxo'    'oxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo:.
'dxxxxxxxxxxxxxxxxxxxxxxxxxxxx:     'oxxxxxxxxxxdl:;;;;;;cONWWWWWWWWW
WWWWWWWWWWNkc;;;;;;;:oxxxxxxxxxxxxxxx:.    .lxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:..
.lxxxxxxxxxxxxxxxxxxxxxxxxxxxd;     'oxxxxxxxxxdl:;;;;;;:kNWWWWWWWWWW
WWWWWWWWWWWNx:;;;;;;;:oxxxxxxxxxxxxxxl'.  .'oxxxxxxxxxxxxxxxxxxxxxxxxxxxxxl,..
.'oxxxxxxxxxxxxxxxxxxxxxxxxxxxxoc;,,;lxxxxxxxxxdc:;;;;;;:xNWWWWWWWWWWW
WWWWWWWWWWWWNkc;;;;;;;:ldxxxxxxxxxxxxxdollodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdollldxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxoc;;;;;;;ckNWWWWWWWWWWWW
WWWWWWWWWWWWWNkc;;;;;;;:cdxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxooxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxdooxxxxxxxxxxxxxxxxxxxxxxo:;;;;;;;ckNWWWWWWWWWWWWW
WWWWWWWWWWWWWWNOl:;;;;;;;:odxxxxxxxxxxxxxxxxxxxxxxxxxxxxl.'oxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxc.'oxxxxxxxxxxxxxxxxxxxdl:;;;;;;;l0WWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWKo:;;;;;;;:cdxxxxxxxxxxxxxxxxxxxxxxxxxxl.
;dxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxl.
;dxxxxxxxxxxxxxxxxdo:;;;;;;;:oKWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWXkc;;;;;;;;:ldxxxxxxxxxxxxxxxxxxxxxxxo'
.cxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo.
.cxxxxxxxxxxxxxxxoc:;;;;;;;ckXWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWN0o:;;;;;;;:cldxxxxxxxxxxxxxxxxxxxxd;
,dxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxd;
,dxxxxxxxxxxxxol:;;;;;;;:o0NWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWXkc;;;;;;;;;cldxxxxxxxxxxxxxxxxxxd,
'oxxxxxxxxxxxxxxxxxxooxxxxxxxxxxxxxxxd,
'dxxxxxxxxxxdl:;;;;;;;;ckXWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWKxc;;;;;;;;;:ldxxxxxxxxxxxxxxxxxo:,,,;ldxxxxxxxxxxxxxxxxxl''oxxxxxxxxxxxxxxxo:,',;lxxxxxxxxdoc:;;;;;;;;cxKWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWN0dc;;;;;;;;;:codxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo'
;dxxxxxxxxxxxxxxxxxxxxxxxxxxxdlc:;;;;;;;;cd0NWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWN0dc;;;;;;;;;:clodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxo,
.cxxxxxxxxxxxxxxxxxxxxxxxxdoc:;;;;;;;;;cd0NWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWNKxc:;;;;;;;;;:clodxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx:.
'dxxxxxxxxxxxxxxxxxxxxdoc:;;;;;;;;;:cxKNWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXko:;;;;;;;;;;::clodxxxxxxxxxxxxxxxxxxxxxxxxxxd;
.oxxxxxxxxxxxxxxxxdolc:;;;;;;;;;;:okXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWN0xl:;;;;;;;;;;;::cloddxxxxxxxxxxxxxxxxxxxxxxo:,'',cdxxxxxxxxxxxddolc:;;;;;;;;;;;:lx0NWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWX0xl:;;;;;;;;;;;;;:cclooddxxxxxxxxxxxxxxxxxxxxxxxxxxxxddoollc::;;;;;;;;;;;;:lx0XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWX0xoc:;;;;;;;;;;;;;;:::ccllloooodddddoddddooooolllcc::;;;;;;;;;;;;;;:cox0XWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKOxoc:;;;;;;;;;;;;;;;;;;;;;::::::::::::;;;;;;;;;;;;;;;;;;;;;:coxOKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNKOkdlc:;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;:cldkOKNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNK0kxolc::;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;::cloxk0KNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNXK0OkxddollcccccccccccccclloodxkO0KXNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNNXXXKKKKKKKKKXXNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
*/

#include <bits/stdc++.h>
using namespace std;

int main() {
  int w;
  cin >> w;
  if (w > 2 && w % 2 == 0)
    cout << "YES" << endl;
  else
    cout << "NO" << endl;
}
